[CmdletBinding(SupportsShouldProcess = $true)]
param(
  [string]$Root,
  [string]$SiteNamePrefix = 'nopayload-',
  [string]$AppPoolName = 'nopayload-static',
  [int]$Port = 80,
  [switch]$SkipHosts,
  [switch]$NoStart,
  [switch]$EnableApiProxy
)

$ErrorActionPreference = 'Stop'

if (-not $Root) {
  $Root = Join-Path $PSScriptRoot '..'
}

$Root = (Resolve-Path $Root).Path
$SitesRoot = Join-Path $Root 'sites'
$AppCmd = Join-Path $env:windir 'System32\inetsrv\appcmd.exe'
$HostsPath = Join-Path $env:windir 'System32\drivers\etc\hosts'

if (-not (Test-Path $AppCmd)) {
  throw "IIS appcmd.exe was not found at $AppCmd. Install/enable IIS before running this script."
}

if (-not (Test-Path $SitesRoot)) {
  throw "Sites folder was not found at $SitesRoot."
}

function Test-IsAdministrator {
  $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
  $principal = [Security.Principal.WindowsPrincipal]::new($identity)
  return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Invoke-AppCmd {
  param([Parameter(Mandatory = $true)][string[]]$Arguments)

  if ($PSCmdlet.ShouldProcess('IIS', "appcmd $($Arguments -join ' ')")) {
    & $script:AppCmd @Arguments
    if ($LASTEXITCODE -ne 0) {
      throw "appcmd failed with exit code $LASTEXITCODE`: $($Arguments -join ' ')"
    }
  }
}

function Test-AppCmd {
  param([Parameter(Mandatory = $true)][string[]]$Arguments)

  & $script:AppCmd @Arguments *> $null
  return $LASTEXITCODE -eq 0
}

function Test-ArrProxyAvailable {
  & $script:AppCmd list config -section:system.webServer/proxy *> $null
  return $LASTEXITCODE -eq 0
}

function Enable-ArrProxy {
  Invoke-AppCmd @(
    'set',
    'config',
    '-section:system.webServer/proxy',
    '/enabled:True',
    '/preserveHostHeader:True',
    '/commit:apphost'
  )
}

function Get-IisSites {
  $xmlText = & $script:AppCmd list site /xml
  if ($LASTEXITCODE -ne 0) {
    throw "Unable to list IIS sites."
  }

  [xml]$xml = ($xmlText -join [Environment]::NewLine)
  return @($xml.appcmd.SITE) | ForEach-Object {
    [pscustomobject]@{
      Name = $_.'SITE.NAME'
      Bindings = @("$($_.bindings)" -split ',' | Where-Object { $_ })
    }
  }
}

function Get-StaticSites {
  Get-ChildItem -Path $script:SitesRoot -Directory | ForEach-Object {
    $siteConfigPath = Join-Path $_.FullName 'site.json'
    if (-not (Test-Path $siteConfigPath)) {
      Write-Warning "Skipping $($_.Name): site.json not found."
      return
    }

    $config = Get-Content -Raw $siteConfigPath | ConvertFrom-Json
    $publicDirName = if ($config.publicDir) { [string]$config.publicDir } else { 'public' }
    $publicPath = Join-Path $_.FullName $publicDirName

    if (-not (Test-Path $publicPath)) {
      Write-Warning "Skipping $($_.Name): public folder not found at $publicPath."
      return
    }

    $aliases = @($config.aliases) | Where-Object { $_ }
    $localHosts = @($aliases | Where-Object { $_ -match '\.local$' })
    if ($localHosts.Count -eq 0) {
      $localHosts = @("$($_.Name).local")
    }

    [pscustomobject]@{
      Slug = $_.Name
      Name = if ($config.siteName) { [string]$config.siteName } else { $_.Name }
      PublicPath = (Resolve-Path $publicPath).Path
      LocalHosts = @($localHosts | Select-Object -Unique)
    }
  }
}

function New-LocalWebConfig {
  param([switch]$ProxyApi)

  $apiRule = ''
  if ($ProxyApi) {
    $apiRule = @'

        <rule name="Proxy admin editor to local Node service" stopProcessing="true">
          <match url="^admin(?:/(.*))?$" ignoreCase="true" />
          <action type="Rewrite" url="http://127.0.0.1:8787/admin/{R:1}" />
        </rule>

        <rule name="Proxy API to local Node service" stopProcessing="true">
          <match url="^api/(.*)$" ignoreCase="true" />
          <action type="Rewrite" url="http://127.0.0.1:8787/api/{R:1}" />
        </rule>
'@
  }

  return @"
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <!-- Auto-generated by scripts/configure-iis-sites.ps1 for local IIS testing. -->
  <system.webServer>
    <handlers>
      <remove name="SSI-html" />
      <remove name="SSI-htm" />
      <add name="SSI-html" path="*.html" verb="GET,HEAD,POST" modules="ServerSideIncludeModule" resourceType="File" requireAccess="Script" />
      <add name="SSI-htm" path="*.htm" verb="GET,HEAD,POST" modules="ServerSideIncludeModule" resourceType="File" requireAccess="Script" />
    </handlers>
    <defaultDocument enabled="true">
      <files>
        <clear />
        <add value="home.html" />
        <add value="index.html" />
      </files>
    </defaultDocument>
    <rewrite>
      <rules>$apiRule
        <rule name="Redirect .html to extensionless" stopProcessing="true">
          <match url="^(.*)\.html$" ignoreCase="true" />
          <conditions>
            <add input="{REQUEST_METHOD}" pattern="^GET$" />
            <add input="{REQUEST_URI}" pattern="^/shared/" negate="true" />
          </conditions>
          <action type="Redirect" url="{R:1}" redirectType="Permanent" />
        </rule>

        <rule name="Rewrite extensionless to .html" stopProcessing="true">
          <match url="^(.*)$" ignoreCase="true" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}.html" matchType="IsFile" />
          </conditions>
          <action type="Rewrite" url="{R:1}.html" />
        </rule>
      </rules>
    </rewrite>
    <httpErrors errorMode="Detailed" />
  </system.webServer>
</configuration>
"@
}

function Set-LocalWebConfig {
  param(
    [Parameter(Mandatory = $true)][string]$PublicPath,
    [switch]$ProxyApi
  )

  $path = Join-Path $PublicPath 'web.config'
  $content = New-LocalWebConfig -ProxyApi:$ProxyApi
  if ($PSCmdlet.ShouldProcess($path, 'write local IIS web.config')) {
    [IO.File]::WriteAllText($path, $content, [Text.UTF8Encoding]::new($false))
  }
}

function Ensure-AppPool {
  if (Test-AppCmd @('list', 'apppool', "/name:$script:AppPoolName")) {
    Write-Host "App pool exists: $script:AppPoolName"
  } else {
    Invoke-AppCmd @('add', 'apppool', "/name:$script:AppPoolName")
  }

  Invoke-AppCmd @(
    'set',
    'apppool',
    "/apppool.name:$script:AppPoolName",
    '/managedRuntimeVersion:',
    '/managedPipelineMode:Integrated'
  )
}

function Ensure-IisSite {
  param([Parameter(Mandatory = $true)]$StaticSite)

  $siteName = "$script:SiteNamePrefix$($StaticSite.Slug)"
  $primaryBinding = 'http/*:{0}:{1}' -f $script:Port, $StaticSite.LocalHosts[0]

  if (Test-AppCmd @('list', 'site', "/name:$siteName")) {
    Write-Host "IIS site exists: $siteName"
    Invoke-AppCmd @('set', 'vdir', "$siteName/", "/physicalPath:$($StaticSite.PublicPath)")
  } else {
    Invoke-AppCmd @(
      'add',
      'site',
      "/name:$siteName",
      "/bindings:$primaryBinding",
      "/physicalPath:$($StaticSite.PublicPath)"
    )
  }

  Invoke-AppCmd @('set', 'app', "$siteName/", "/applicationPool:$script:AppPoolName")

  $iisSites = @(Get-IisSites)
  $currentSite = $iisSites | Where-Object { $_.Name -eq $siteName } | Select-Object -First 1

  foreach ($hostName in $StaticSite.LocalHosts) {
    $binding = 'http/*:{0}:{1}' -f $script:Port, $hostName
    $conflict = $iisSites | Where-Object {
      $_.Name -ne $siteName -and $_.Bindings -contains $binding
    } | Select-Object -First 1

    if ($conflict) {
      Write-Warning "Binding $binding is already owned by IIS site '$($conflict.Name)'. Skipping that binding for $siteName."
      continue
    }

    if ($currentSite -and $currentSite.Bindings -contains $binding) {
      Write-Host "Binding exists: $binding"
      continue
    }

    Invoke-AppCmd @(
      'set',
      'site',
      "/site.name:$siteName",
      ("/+bindings.[protocol='http',bindingInformation='*:{0}:{1}']" -f $script:Port, $hostName)
    )
  }

  if (-not $NoStart) {
    Invoke-AppCmd @('start', 'site', "/site.name:$siteName")
  }
}

function Update-HostsFile {
  param([Parameter(Mandatory = $true)][string[]]$HostNames)

  if ($SkipHosts) {
    Write-Host 'Skipping hosts file update because -SkipHosts was passed.'
    return
  }

  if (-not (Test-IsAdministrator)) {
    Write-Warning "Hosts file update requires an elevated PowerShell session. Add these manually or rerun as Administrator: $($HostNames -join ', ')"
    return
  }

  $begin = '# BEGIN nopayload local sites'
  $end = '# END nopayload local sites'
  $newline = [Environment]::NewLine
  $content = if (Test-Path $HostsPath) { Get-Content -Raw $HostsPath } else { '' }
  $pattern = "(?ms)^[ \t]*$([regex]::Escape($begin)).*?$([regex]::Escape($end))[ \t]*(\r?\n)?"
  $clean = [regex]::Replace($content, $pattern, '')

  $entries = @($HostNames | Sort-Object -Unique | ForEach-Object { "127.0.0.1 $_" })
  $block = @($begin) + $entries + @($end)
  $newContent = $clean.TrimEnd() + $newline + $newline + ($block -join $newline) + $newline

  if ($PSCmdlet.ShouldProcess($HostsPath, 'write nopayload local host entries')) {
    [IO.File]::WriteAllText($HostsPath, $newContent, [Text.UTF8Encoding]::new($false))
  }
}

$staticSites = @(Get-StaticSites)
if ($staticSites.Count -eq 0) {
  throw "No static sites found under $SitesRoot."
}

if ($EnableApiProxy -and -not (Test-ArrProxyAvailable)) {
  Write-Warning 'IIS ARR proxy support is not installed/enabled, so /api/* proxy rules will not be written. Install Application Request Routing if local IIS must proxy the Node API.'
  $EnableApiProxy = $false
}

Write-Host "Configuring $($staticSites.Count) IIS site(s) from $SitesRoot"
if ($EnableApiProxy) {
  Enable-ArrProxy
}

Ensure-AppPool

$allLocalHosts = @()
foreach ($site in $staticSites) {
  Write-Host ""
  Write-Host "Site: $($site.Slug) -> $($site.PublicPath)"
  Write-Host "Hosts: $($site.LocalHosts -join ', ')"
  Set-LocalWebConfig -PublicPath $site.PublicPath -ProxyApi:$EnableApiProxy
  Ensure-IisSite -StaticSite $site
  $allLocalHosts += $site.LocalHosts
}

Update-HostsFile -HostNames $allLocalHosts

Write-Host ""
Write-Host 'Local IIS site configuration complete.'
foreach ($site in $staticSites) {
  foreach ($hostName in $site.LocalHosts) {
    Write-Host "http://$hostName/"
  }
}
